import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@splidejs/react-splide/css";
import "@splidejs/react-splide/css/core";
import "@splidejs/react-splide/css/skyblue";
import "@splidejs/react-splide/css/sea-green";
import "./globals.css";
import UIHeader from "~/components/UIHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative max-w-full w-full z-50">
          <UIHeader />
        </div>
        {children}
      </body>
    </html>
  );
}
